version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80"
    environment:
      DATABASE_URL: mysql+pymysql://mika:mika2306@host.docker.internal/items
    depends_on:
      - db
    networks:
      - my-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fastapi_db
      MYSQL_USER: mika
      MYSQL_PASSWORD: mika2306
    ports:
      - "3307:3306"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
