version: "3.7"

services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: fastapi_mysql_app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    volumes:
      - ./app:/app
    ports:
      - "8000:80"
    depends_on:
      - db

volumes:
  db_data:
